const constants = {
    ADD_PODCAST: "ADD_PODCAST",
    ADD_PODCAST_IMG_FP:"ADD_PODCAST_IMG_FP",
    REMOVE_PODCAST: "REMOVE_PODCAST",
    GET_PODCAST_INFO:"GET_PODCAST_INFO",
    HANDLE_ERROR:"HANDLE_ERROR",
    CHANGE_SELECTED_PODCAST:'CHANGE_SELECTED_PODCAST', 
    CURRENT_EPISODE:'CURRENT_EPISODE',
}

export default constants