# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodcastApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PodcastApp
  #pod 'RNAudioStreaming', :path => '../node_modules/react-native-audio-streaming'

  target 'PodcastAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PodcastApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PodcastApp-tvOS

  target 'PodcastApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
